### ISSUE TITLE
NameError: name 'mp4' is not defined

### ISSUE THREAD

**Issue by Pepe-77777** [JohannSuarez/chroma_blend#16]
I'm trying to make this run on google colab, but even following all the steps, it returns this:

```
Traceback (most recent call last):
  File "chroma_blend.py", line 17, in <module>
    class CBlend:
  File "chroma_blend.py", line 70, in CBlend
    def png2mp4(self: object, vidin: str)  -> mp4: 
NameError: name 'mp4' is not defined
```

**Comment by Pepe-77777** [comment]
Resolved deleting the code and put FFmpeg to do the function.
